### ISSUE TITLE
Transcript & user tables not working in admin view on prod

### ISSUE THREAD

**Issue by tamsingreen** [bbc/digital-paper-edit-firebase#239]
Transcripts and User tabs of the Admin view on prod not loading table data.
Console shows permission errors.
<img width="1110" alt="Screenshot 2021-05-11 at 12 12 16" src="https://user-images.githubusercontent.com/6200644/117806421-3f0fe200-b252-11eb-914f-8310659a8a74.png">

**Comment by allishultes** [comment]
This happened because the dpe-admin user did not have ADMIN set as its role in Firebase. This is documented in [Eimi's document on the admin view](https://github.com/bbc/digital-paper-edit-firebase/blob/master/docs/guides/admin-view.md) so I won't add it to the new document on bugs we encountered while setting up a new environment. I've changed this in the console and can confirm it works for me now.
